baseURL = "https://ajayvijayakumar123.github.io"
languageCode = "en-us"
title = "Ajay Vijayakumar"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""
publishDir = "ajayvijayakumar123.github.io"

[params]
    author = "Ajay Vijayakumar"
    description = "Hi, I'm a CS major at Georgia Tech! I enjoy playing basketball, reading, and journaling my dreams."
    githubUsername = "#ajayvijayakumar123"
    # accent = "white"
    showBorder = false
    backgroundColor = "white"
    font = "Calibri" # should match the name on Google Fonts!
    highlight = false
    highlightStyle = "default"
    highlightLanguages = ["java", "python", "javascript"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/resume/resume"
    name = "Resume"
    weight = 3

#[[menu.main]]
    #url = "/post/"
    #name = "Posts"
    #weight = 3

#[[menu.main]]
    #url = "/project/"
    #name = "Projects"
    #weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "https://github.com/ajayvijayakumar123"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://www.linkedin.com/in/ajayvijayakumar1/"
    name = "linkedin"
    weight = 2

[[menu.icon]]
    url = "https://www.instagram.com/ajay.pdf/"
    name = "instagram"
    weight = 3